apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-pwd: bXlzcWwtZGF0YWJhc2Utcm9vdC1wYXNzd29yZA==

secretGenerator:
- name: mysql-pass
  literals:
  - password=bXlzcWwtZGF0YWJhc2Utcm9vdC1wYXNzd29yZA==
