apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-label
spec:
  selector:
    app: mysql-label
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 # Target Container Port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-label
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-label
    spec:
      containers:
      - name: mysql-container
        image: mysql-img
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-pwd
