apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-label
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin-label
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin-label
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: phpmyadmin-label
  template:
    metadata:
      labels:
        app: phpmyadmin-label
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin-container
        # imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: mysql-service
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: root
