apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-label
spec:
  type: NodePort
  selector:
    app: phpmyadmin-label
  ports:
  - port: 5000
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin-label
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: phpmyadmin-label
  template:
    metadata:
      labels:
        app: phpmyadmin-label
    spec:
      containers:
      - image: phpmyadmin:fpm-alpine
        name: phpmyadmin-container
        # imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: PMA_HOST
          value: mysql-service
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: root
