apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-label
spec:
  selector:
    app: phpmyadmin-label
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-label
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: phpmyadmin-label
    spec:
      containers:
      - name: phpmyadmin-container
        image: phpmyadmin-img
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: phpmyadmin-configmap
              key: database_url
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-pwd
