apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  db_name: d29yZHByZXNzLW5hbWU=
  db_user: d29yZHByZXNzLXVzZXJuYW1l
  db_host: d29yZHByZXNzLWhvc3Q=
  db_password: d29yZHByZXNzLXBhc3N3b3Jk
