apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress-label
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-label
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress-label
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-label
spec:
  selector:
    matchLabels:
      app: wordpress-label
      tier: frontend
  strategy:
    type: Recreate
    # strategy: type: Recreate in the Deployment configuration YAML file.
    # This instructs Kubernetes to not use rolling updates.
    # Rolling updates will not work, as you cannot have more than one Pod running at a time.
    # The Recreate strategy will stop the first pod before creating a new one with the updated configuration.
  template:
    metadata:
      labels:
        app: wordpress-label
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress-container
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_PASSWORD
          value: root
        ports:
        - containerPort: 80
          name: wordpress-label
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
