apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress-label
spec:
  type: LoadBalancer
  selector:
    app: wordpress-label
  ports:
    - port: 5050
      name: http
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-label
spec:
  selector:
    matchLabels:
      app: wordpress-label
  replicas: 1
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress-label
    spec:
      containers:
        - name: wordpress-container
          image: wordpress-img
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
              name: http
          env:
            - name: DB_NAME
              valueFrom:
                    secretKeyRef:
                      name: wordpress-secret
                      key: db_name
            - name: DB_USER
              valueFrom:
                    secretKeyRef:
                      name: wordpress-secret
                      key: db_user
            - name: DB_HOST
              valueFrom:
                    secretKeyRef:
                      name: wordpress-secret
                      key: db_host
            - name: DB_PASSWORD
              valueFrom:
                    secretKeyRef:
                      name: wordpress-secret
                      key: db_password
