apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress-label
spec:
  selector:
    app: wordpress-label
  type: LoadBalancer
  ports:
    - port: 5050
      name: port
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-label
spec:
  selector:
    matchLabels:
      app: wordpress-label
  replicas: 1
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress-label
    spec:
      containers:
        - name: wordpress-container
          image: wordpress-img
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
